Fix KeyError for missing password
This fixes the following exception:

Traceback (most recent call last):
  File "/home/zuul/.ansible/tmp/ansible-local-18185o2i5gpv3/ansible-tmp-1575493126.9313893-235076820443659/AnsiballZ_nxos_user.py", line 116, in <module>
    _ansiballz_main()
  File "/home/zuul/.ansible/tmp/ansible-local-18185o2i5gpv3/ansible-tmp-1575493126.9313893-235076820443659/AnsiballZ_nxos_user.py", line 108, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/zuul/.ansible/tmp/ansible-local-18185o2i5gpv3/ansible-tmp-1575493126.9313893-235076820443659/AnsiballZ_nxos_user.py", line 54, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.nxos.nxos_user', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_nxos_user_payload_iv33p1sn/ansible_nxos_user_payload.zip/ansible/modules/network/nxos/nxos_user.py", line 379, in <module>
  File "/tmp/ansible_nxos_user_payload_iv33p1sn/ansible_nxos_user_payload.zip/ansible/modules/network/nxos/nxos_user.py", line 341, in main
KeyError: 'password'

Signed-off-by: Paul Belanger <pabelanger@redhat.com>